src/Entity/Ingredient.php
<?php

namespace App\Entity;

use App\Repository\IngredientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="ingredients")
 * @ORM\Entity(repositoryClass=IngredientRepository::class)
 */
class Ingredient
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ingredient_name;

    /**
     * @ORM\Column(type="float")
     */
    private $ingredient_price;

    /**
     * @ORM\Column(type="boolean")
     */
    private $vegetarian;

    /**
     * @ORM\Column(type="boolean")
     */
    private $vegan;

    /**
     * @ORM\ManyToMany(targetEntity=Pizza::class, mappedBy="pizza_ingredients")
     */
    private $pizzas;

    public function __construct()
    {
        $this->pizzas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIngredientName(): ?string
    {
        return $this->ingredient_name;
    }

    public function setIngredientName(string $ingredient_name): self
    {
        $this->ingredient_name = $ingredient_name;

        return $this;
    }

    public function getIngredientPrice(): ?float
    {
        return $this->ingredient_price;
    }

    public function setIngredientPrice(float $ingredient_price): self
    {
        $this->ingredient_price = $ingredient_price;

        return $this;
    }

    public function getVegetarian(): ?bool
    {
        return $this->vegetarian;
    }

    public function setVegetarian(?bool $vegetarian): self
    {
        $this->vegetarian = $vegetarian;

        return $this;
    }

    public function getVegan(): ?bool
    {
        return $this->vegan;
    }

    public function setVegan(bool $vegan): self
    {
        $this->vegan = $vegan;

        return $this;
    }

    /**
     * @return Collection|Pizza[]
     */
    public function getPizzas(): Collection
    {
        return $this->pizzas;
    }

    public function addPizza(Pizza $pizza): self
    {
        if (!$this->pizzas->contains($pizza)) {
            $this->pizzas[] = $pizza;
            $pizza->addPizzaIngredient($this);
        }

        return $this;
    }

    public function removePizza(Pizza $pizza): self
    {
        if ($this->pizzas->removeElement($pizza)) {
            $pizza->removePizzaIngredient($this);
        }

        return $this;
    }
}

src/Form/IngredientType.php
<?php

namespace App\Form;

use App\Entity\Ingredient;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class IngredientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('ingredient_name',TextType::class, ["label" => "Ingrédient"])
            ->add('ingredient_price',NumberType::class, ["label" => "Prix"])
            ->add('vegetarian', ChoiceType::class,[
                "choices" => [
                    "Oui" => true,
                    "Non" => false
                ]
            ])
            ->add('vegan', ChoiceType::class,[
                "choices" => [
                    "Oui" => true,
                    "Non" => false
                ]
            ])
//            ->add('pizzas')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ingredient::class,
        ]);
    }
}

src/Controller/IngredientController.php
<?php

namespace App\Controller;

use App\Entity\Ingredient;
use App\Form\IngredientType;
use App\Repository\IngredientRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ingredient")
 */
class IngredientController extends AbstractController
{
    /**
     * @Route("/", name="ingredient_index", methods={"GET"})
     */
    public function index(IngredientRepository $ingredientRepository): Response
    {
        return $this->render('ingredient/index.html.twig', [
            'ingredients' => $ingredientRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="ingredient_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $ingredient = new Ingredient();
        $form = $this->createForm(IngredientType::class, $ingredient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ingredient);
            $entityManager->flush();

            return $this->redirectToRoute('ingredient_index');
        }

        return $this->render('ingredient/new.html.twig', [
            'ingredient' => $ingredient,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ingredient_show", methods={"GET"})
     */
    public function show(Ingredient $ingredient): Response
    {
        return $this->render('ingredient/show.html.twig', [
            'ingredient' => $ingredient,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="ingredient_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Ingredient $ingredient): Response
    {
        $form = $this->createForm(IngredientType::class, $ingredient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('ingredient_index');
        }

        return $this->render('ingredient/edit.html.twig', [
            'ingredient' => $ingredient,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ingredient_delete", methods={"POST"})
     */
    public function delete(Request $request, Ingredient $ingredient): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ingredient->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ingredient);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ingredient_index');
    }
}

templates/ingredient/_delete_form.html.twig
<form method="post" action="{{ path('ingredient_delete', {'id': ingredient.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ingredient.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/ingredient/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}

<div class="flex">
    <div><button  class="btn btn-primary">{{ button_label|default('Save') }}</button></div>
{{ form_end(form) }}

templates/ingredient/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Ingredient{% endblock %}

{% block body %}
    <h1>Modifier un ingredient</h1>

    {{ include('ingredient/_form.html.twig', {'button_label': 'Update'}) }}

{#    <a href="{{ path('ingredient_index') }}">back to list</a>#}

    {{ include('ingredient/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/ingredient/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des ingrédients{% endblock %}

{% block body %}
    <h1>Liste des ingrédients</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Dénomination</th>
                <th>prix</th>
                <th>Vegetarien</th>
                <th>Vegan</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for ingredient in ingredients %}
            <tr>
                <td>{{ ingredient.ingredientName }}</td>
                <td>{{ ingredient.ingredientPrice }} €</td>
                <td>{{ ingredient.vegetarian ? 'Yes' : 'No' }}</td>
                <td>{{ ingredient.vegan ? 'Yes' : 'No' }}</td>
                <td class="flex">
                    <div><a class="btn btn-success" href="{{ path('ingredient_show', {'id': ingredient.id}) }}">show</a></div>
                    <div><a class="btn btn-warning" href="{{ path('ingredient_edit', {'id': ingredient.id}) }}">edit</a></div>
                    {{ include('ingredient/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('ingredient_new') }}">Create new</a>
{% endblock %}

templates/ingredient/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Ingredient{% endblock %}

{% block body %}
    <h1>Create new Ingredient</h1>

    {{ include('ingredient/_form.html.twig') }}

{#    <a class="btn btn-warning" href="{{ path('ingredient_index') }}">back to list</a>#}
{% endblock %}

templates/ingredient/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ingredient{% endblock %}

{% block body %}
    <h1>Ingredient</h1>

    <table class="table">
        <thead>
        <tr><th colspan="2" class="center big">{{ ingredient.ingredientName }}</th></tr>
        </thead>
        <tbody>
            <tr>
                <th class="center ">Prix</th>
                <td>{{ ingredient.ingredientPrice }} €</td>
            </tr>
            <tr>
                <th class="center">Vegetarian ?</th>
                <td>{{ ingredient.vegetarian ? 'Oui' : 'Non' }}</td>
            </tr>
            <tr>
                <th class="center">Vegan ?</th>
                <td>{{ ingredient.vegan ? 'Oui' : 'Non' }}</td>
            </tr>
        </tbody>
    </table>

    <div class="flex flex-center">
        {#    <a href="{{ path('ingredient_index') }}">back to list</a>#}
        <div><a class="btn btn-warning" href="{{ path('ingredient_edit', {'id': ingredient.id}) }}">edit</a></div>

        {{ include('ingredient/_delete_form.html.twig') }}
    </div>
{% endblock %}