src/Entity/Base.php
<?php

namespace App\Entity;

use App\Repository\BaseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="bases")
 * @ORM\Entity(repositoryClass=BaseRepository::class)
 */
class Base
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $base_name;

    /**
     * @ORM\Column(type="float")
     */
    private $base_price;

    /**
     * @ORM\OneToMany(targetEntity=Pizza::class, mappedBy="pizza_base")
     */
    private $pizzas;

    public function __construct()
    {
        $this->pizzas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBaseName(): ?string
    {
        return $this->base_name;
    }

    public function setBaseName(string $base_name): self
    {
        $this->base_name = $base_name;

        return $this;
    }

    public function getBasePrice(): ?float
    {
        return $this->base_price;
    }

    public function setBasePrice(float $base_price): self
    {
        $this->base_price = $base_price;

        return $this;
    }

    /**
     * @return Collection|Pizza[]
     */
    public function getPizzas(): Collection
    {
        return $this->pizzas;
    }

    public function addPizza(Pizza $pizza): self
    {
        if (!$this->pizzas->contains($pizza)) {
            $this->pizzas[] = $pizza;
            $pizza->setPizzaBase($this);
        }

        return $this;
    }

    public function removePizza(Pizza $pizza): self
    {
        if ($this->pizzas->removeElement($pizza)) {
            // set the owning side to null (unless already changed)
            if ($pizza->getPizzaBase() === $this) {
                $pizza->setPizzaBase(null);
            }
        }

        return $this;
    }

    public function getBasePriceByID($id): ?float
    {
        $getBase = $this->findOneBy(["id" => $id]);
        $getBasePrice = $getBase->getBasePrice();

        return $getBasePrice;
    }
}

src/Entity/Ingredient.php
<?php

namespace App\Entity;

use App\Repository\IngredientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="ingredients")
 * @ORM\Entity(repositoryClass=IngredientRepository::class)
 */
class Ingredient
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ingredient_name;

    /**
     * @ORM\Column(type="float")
     */
    private $ingredient_price;

    /**
     * @ORM\Column(type="boolean")
     */
    private $vegetarian;

    /**
     * @ORM\Column(type="boolean")
     */
    private $vegan;

    /**
     * @ORM\ManyToMany(targetEntity=Pizza::class, mappedBy="pizza_ingredients")
     */
    private $pizzas;

    public function __construct()
    {
        $this->pizzas = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIngredientName(): ?string
    {
        return $this->ingredient_name;
    }

    public function setIngredientName(string $ingredient_name): self
    {
        $this->ingredient_name = $ingredient_name;

        return $this;
    }

    public function getIngredientPrice(): ?float
    {
        return $this->ingredient_price;
    }

    public function setIngredientPrice(float $ingredient_price): self
    {
        $this->ingredient_price = $ingredient_price;

        return $this;
    }

    public function getVegetarian(): ?bool
    {
        return $this->vegetarian;
    }

    public function setVegetarian(?bool $vegetarian): self
    {
        $this->vegetarian = $vegetarian;

        return $this;
    }

    public function getVegan(): ?bool
    {
        return $this->vegan;
    }

    public function setVegan(bool $vegan): self
    {
        $this->vegan = $vegan;

        return $this;
    }

    /**
     * @return Collection|Pizza[]
     */
    public function getPizzas(): Collection
    {
        return $this->pizzas;
    }

    public function addPizza(Pizza $pizza): self
    {
        if (!$this->pizzas->contains($pizza)) {
            $this->pizzas[] = $pizza;
            $pizza->addPizzaIngredient($this);
        }

        return $this;
    }

    public function removePizza(Pizza $pizza): self
    {
        if ($this->pizzas->removeElement($pizza)) {
            $pizza->removePizzaIngredient($this);
        }

        return $this;
    }
}

src/Entity/Pizza.php
<?php

namespace App\Entity;

use App\Repository\PizzaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="pizzas")
 * @ORM\Entity(repositoryClass=PizzaRepository::class)
 */
class Pizza
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $pizza_name;

    /**
     * @ORM\ManyToOne(targetEntity=Base::class, inversedBy="pizzas")
     * @ORM\JoinColumn(nullable=false)
     */
    private $pizza_base;

    /**
     * @ORM\ManyToOne(targetEntity=Size::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $pizza_size;

    /**
     * @ORM\ManyToMany(targetEntity=Ingredient::class, inversedBy="pizzas")
     */
    private $pizza_ingredients;

    public function __construct()
    {
        $this->pizza_ingredients = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPizzaName(): ?string
    {
        return $this->pizza_name;
    }

    public function setPizzaName(string $pizza_name): self
    {
        $this->pizza_name = $pizza_name;

        return $this;
    }

    public function getPizzaBase(): ?Base
    {
        return $this->pizza_base;
    }

    public function setPizzaBase(?Base $pizza_base): self
    {
        $this->pizza_base = $pizza_base;

        return $this;
    }

    public function getPizzaSize(): ?Size
    {
        return $this->pizza_size;
    }

    public function setPizzaSize(?Size $pizza_size): self
    {
        $this->pizza_size = $pizza_size;

        return $this;
    }

    /**
     * @return Collection|Ingredient[]
     */
    public function getPizzaIngredients(): Collection
    {
        return $this->pizza_ingredients;
    }

    public function addPizzaIngredient(Ingredient $pizzaIngredient): self
    {
        if (!$this->pizza_ingredients->contains($pizzaIngredient)) {
            $this->pizza_ingredients[] = $pizzaIngredient;
        }

        return $this;
    }

    public function removePizzaIngredient(Ingredient $pizzaIngredient): self
    {
        $this->pizza_ingredients->removeElement($pizzaIngredient);

        return $this;
    }

    public function getPizzaPrice(): float
    {
        $basePrice = $this->pizza_base->getBasePrice();
        $sizePrice = $this->pizza_size->getSizePrice();

        $ingredients = 0;
        foreach ($this->pizza_ingredients as $ingredient){
            $ingredients += $ingredient->getIngredientPrice();
        }

        $result = $basePrice + $sizePrice + $ingredients;

        return $result;
    }

    public function isVegiOrVegan(): string
    {
        $isVegi = true;
        $isVegan = true;

        foreach ($this->pizza_ingredients as $ingredient){
            $ingredientVegi = $ingredient->getVegetarian();
            $ingredientVegan = $ingredient->getVegan();

            if ($ingredientVegan == false) {
                $isVegan = false;
            }
            if ($ingredientVegi == false) {
                $isVegi = false;
            }
        }

        if($isVegan == true){
            $result = "Végan";
        } else if ($isVegi == true){
            $result = "Végétarien";
        } else {
            $result = "";
        }

        return $result;
    }
}

src/Entity/Size.php
<?php

namespace App\Entity;

use App\Repository\SizeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="sizes")
 * @ORM\Entity(repositoryClass=SizeRepository::class)
 */
class Size
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $size_name;

    /**
     * @ORM\Column(type="float")
     */
    private $size_price;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSizeName(): ?string
    {
        return $this->size_name;
    }

    public function setSizeName(string $size_name): self
    {
        $this->size_name = $size_name;

        return $this;
    }

    public function getSizePrice(): ?float
    {
        return $this->size_price;
    }

    public function setSizePrice(float $size_price): self
    {
        $this->size_price = $size_price;

        return $this;
    }
}

src/Form/PizzaType.php
<?php

namespace App\Form;

use App\Entity\Base;
use App\Entity\Ingredient;
use App\Entity\Pizza;
use App\Entity\Size;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PizzaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('pizza_name',TextType::class, ["label" => "Nom de la Pizza"])
            ->add('pizza_base', EntityType::class, [
                "label" => "Base de la Pizza",
                "class" => Base::class,
                "choice_label" => function ($size) {
                    return $size->getBaseName() . " - " . $size->getBasePrice() ."€";
                }
            ])
            ->add('pizza_size', EntityType::class, [
                "label" => "Taille de la Pizza",
                "class" => Size::class,
                "choice_label" => function ($size) {
                    return $size->getSizeName() . " - " . $size->getSizePrice() ."€";
                }
            ])
            ->add('pizza_ingredients', EntityType::class, [
                "label" => "Choix Ingrédients",
                "class" => Ingredient::class,
                "choice_label" => function ($ingredient) {
                    return $ingredient->getIngredientName() . " - " . $ingredient->getIngredientPrice() ."€";
                },
                "multiple" => true,
                "expanded" => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pizza::class,
        ]);
    }
}

src/Controller/PizzaController.php
<?php

namespace App\Controller;

use App\Entity\Pizza;
use App\Form\PizzaType;
use App\Repository\PizzaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/pizza")
 */
class PizzaController extends AbstractController
{
    /**
     * @Route("/", name="pizza_index", methods={"GET"})
     */
    public function index(PizzaRepository $pizzaRepository): Response
    {
        return $this->render('pizza/index.html.twig', [
            'pizzas' => $pizzaRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="pizza_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $pizza = new Pizza();
        $form = $this->createForm(PizzaType::class, $pizza);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($pizza);
            $entityManager->flush();

            return $this->redirectToRoute('pizza_index');
        }

        return $this->render('pizza/new.html.twig', [
            'pizza' => $pizza,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pizza_show", methods={"GET"})
     */
    public function show(Pizza $pizza): Response
    {
        return $this->render('pizza/show.html.twig', [
            'pizza' => $pizza,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="pizza_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Pizza $pizza): Response
    {
        $form = $this->createForm(PizzaType::class, $pizza);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('pizza_index');
        }

        return $this->render('pizza/edit.html.twig', [
            'pizza' => $pizza,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="pizza_delete", methods={"POST"})
     */
    public function delete(Request $request, Pizza $pizza): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pizza->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($pizza);
            $entityManager->flush();
        }

        return $this->redirectToRoute('pizza_index');
    }
}

templates/pizza/_delete_form.html.twig
<form method="post" action="{{ path('pizza_delete', {'id': pizza.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pizza.id) }}">
    <button class="btn btn-danger btn-block">Delete</button>
</form>

templates/pizza/_form.html.twig
{{ form_start(form) }}

    {{ form_widget(form) }}
    <br>

    <h3>Prix de la pizza:  </h3>
<div class="flex">
    <div><button class="btn btn-primary">{{ button_label|default('Save') }}</button></div>

    <script>
        // Récup Base ID
        var base = document.getElementById("pizza_pizza_base");
        var size = document.getElementById("pizza_pizza_size");
        var ingredientDiv = document.getElementById("pizza_pizza_ingredients");
        var ingredients = ingredientDiv.getElementsByTagName("input");
        var ingredientList = ingredientDiv.childNodes;
        // console.log(ingredientList.length);

        function getBasePrice () {
            console.log(base.value);
            var baseId = base.value;
            return baseId;
        }
        function getSizePrice () {
            console.log(size.value);
            var sizeId = size.value;
            return sizeId;
        }
        function getIngredientPrice () {
            // tableau contenant la liste des id des checkbox checked
            var tabIngredientPrice = [];

            console.log("OK")
            // boucle sur chaque checkbox des ingrédients pour vérifier s'ils sont coché
            // puis récupérer leur id et les ajouter au tableau
            for (var i = 0; i < ingredientList.length; i++) {
                var ingredientId = document.getElementById("pizza_pizza_size_" + i)
                if (ingredientId.checked){
                    tabIngredientPrice += ingredientId.value;
                }
            }
            for (var i = 0; i < tabIngredientPrice.length; i++) {
                console.log(tabIngredientPrice[i]);
            }
            return tabIngredientPrice;
        }

        base.onchange = getBasePrice;
        size.onchange = getSizePrice;
        ingredients.onchange = getIngredientPrice;

        // console.log(base);

        // var getBasePrice = getBasePrice();
    </script>
{{ form_end(form) }}

templates/pizza/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Pizza{% endblock %}

{% block body %}
    <h1>Edit Pizza</h1>

    {{ include('pizza/_form.html.twig', {'button_label': 'Update'}) }}

{#    <a href="{{ path('pizza_index') }}">back to list</a>#}

    {{ include('pizza/_delete_form.html.twig') }}
    </div>
{% endblock %}

templates/pizza/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Listes des Pizzas{% endblock %}

{% block body %}
    <h1>Listes des Pizzas</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Taille</th>
                <th>Base</th>
                <th>Prix</th>
                <th>Végétarien/Vegan</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for pizza in pizzas %}
            <tr>
                <td>{{ pizza.pizzaName }}</td>
                <td>{{ pizza.pizzaSize.sizeName }}</td>
                <td>{{ pizza.pizzaBase.baseName }}</td>
                <td>{{ pizza.pizzaPrice }} €</td>
                <td>{{ pizza.isVegiOrVegan }}</td>
                <td class="flex">
                    <div><a class="btn btn-success" href="{{ path('pizza_show', {'id': pizza.id}) }}">show</a></div>
                    <div><a class="btn btn-warning" href="{{ path('pizza_edit', {'id': pizza.id}) }}">edit</a></div>
                    {{ include('pizza/_delete_form.html.twig') }}
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>

    </table>

    <a class="btn btn-primary" href="{{ path('pizza_new') }}">Create new</a>
{% endblock %}

templates/pizza/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pizza{% endblock %}

{% block body %}
    <h1>Create new Pizza</h1>

    {{ include('pizza/_form.html.twig') }}

{#    <a class="btn btn-warning" href="{{ path('pizza_index') }}">back to list</a>#}
{% endblock %}

templates/pizza/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pizza{% endblock %}

{% block body %}

    <table class="table">

        <thead>
            <tr>
                <th class="center big">Pizza {{ pizza.pizzaName }}</th>
                <th class="center big">{{ pizza.pizzaPrice }} €</th>
            </tr>
        </thead>
        <tbody class="center">
            <tr>
                <th>Base</th>
                <th>Taille</th>
            </tr>
            <tr>
                <td>{{ pizza.pizzaBase.baseName }}</td>
                <td>{{ pizza.pizzaSize.sizeName }}</td>
            </tr>
        </tbody>
        <tbody>
            <tr>
                <th>ingrédients :</th>
            </tr>
            {% for ingredient in pizza.pizzaIngredients %}
                <tr><td>{{ ingredient.ingredientName }}</td></tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="flex flex-center">
        {#    <a href="{{ path('pizza_index') }}">back to list</a>#}
        <div><a class="btn btn-warning" href="{{ path('pizza_edit', {'id': pizza.id}) }}">Modifier</a></div>

        {{ include('pizza/_delete_form.html.twig') }}

{% endblock %}